#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Nov 15 14:27:56 2019

@author: tdh
"""
import numpy as np


def find_max_vec(vec):
    """
    Returns the action to take given a certain state.

    Parameters
    ------------
    vec : array
    
    Returns
    ----------
    (maxi, max_indexes)
    maxi: float
    maximum value in array
    max_indexes: list
    list of indexes of maximum value in array
    
    """
    
    max_indexes=[]
    maxi= vec.max()
    for i in range(np.size(vec)):
        if vec[i]==maxi:
            max_indexes.append(i)
    return(maxi, max_indexes)
    
a=np.array([[1,2,3,4,5,6],[11,12,13,14,15,16],[21,22,23,24,25,26]])

print(find_max_vec(a[:,5]))

print(a)