#This file is a YAML file to contain the different parametres

request_rate: [10,100,1000]
interval_size: [1,10]
delta1: [20,50,100]
method: ['SARSA', 'Q_learning','SPSA']
D: [[1], [1, 2], [1, 2, 4, 8]]  #space of Delta